name: Build Typst document
on: 
  workflow_run:
    workflows: ["Tag"]
    types: [completed]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            Segundo/Cuatri1/meca.typ
            Segundo/Cuatri1/mmat2.typ
            Segundo/Cuatri1/termo.typ
            Segundo/Cuatri2/fest.typ
            Segundo/Cuatri2/campos.typ
            Segundo/Cuatri2/fluidos.typ
          options: |
            --root
            .
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "latest"
          files: |
            Segundo/Cuatri1/meca.pdf
            Segundo/Cuatri1/mmat2.pdf
            Segundo/Cuatri1/termo.pdf
            Segundo/Cuatri2/fest.pdf
            Segundo/Cuatri2/campos.pdf
            Segundo/Cuatri2/fluidos.pdf